### ISSUE TITLE
Dudas gráficos

### ISSUE THREAD

**Issue by VeraGD** [VeraGD/Actividad_Fisica#15]
Duda 1:
* Seguimos sin saber como relacionar los conceptos para que se entienda y se pueda apreciar. Tenemos varias opciones de gráficos y representaciones. 
     - Para representar el número de personas con ansiedad y depresión en porcentaje y de las personas que realizan ejercicio físico por días a la semana. 
     - Por una parte, tenemos un gráfico en el que utilizamos geom_violin: en el eje x tenemos los valores máximos de personas que realizan ejercicio por comunidades (lo que te preguntamos en clase), y el porcentaje de personas con ansiedad y depresión.
     - Tiene algo de sentido el gráfico, porque no mucho.
* Podemos representar los valores máximos (imagen 1), o los diferentes valores para cada día de la semana con un facet_wrap (imagen 2). 
  
![WhatsApp Image 2021-12-01 at 17 35 30](https://user-images.githubusercontent.com/80346356/144275571-f332bd6a-b83c-47fc-ad04-599bcfc92eb1.jpeg)
 
![WhatsApp Image 2021-12-01 at 17 50 50](https://user-images.githubusercontent.com/80346356/144277452-a1126e49-d212-441f-9688-2cdf5f8bd1de.jpeg)

**Comment by ajcanepa** [comment]
De ambas gráficas, yo solo puedo (con un poco de esfuerzo) entender la segunda. De esta segunda gráfica y asumiendo que el eje X "habla" de un gradiente de actividad física, veo que:

- En general a mayor actividad física hay un descenso de los niveles de depresión y ansiedad.
- En general, a un nivel bajo de actividad física hay un aumento considerable de ansiedad y depresión (muy curioso!!)
- Para ambos trastornos, la bajada en afectación (menor ansiedad y menor depresión), es decir la pendiente de bajada es menor, se da  cuando se practica más deporte (7 días a la semana). 

Dudas:
Sino vas a sacarle información a las CCAA, no pintéis los puntos porque distrae (yo no los pintaría a no ser que hubiera algo que "rascar" de ellos).
No termino de entender en qué se diferencia la "Frecuencia de Actividad Física (eje X)" con los paneles de "d1_2", "d3_4", etc. ¿Acaso el número de días a la semana que se practica actividad física no es similar a la frecuencia de actividad física?

Si realmente son conceptos diferentes (y los podéis explicar) yo intentaría graficar (para cada enfermedad) un sólo gráfico de Frecuencia Actv. Física (eje x) v/s Nº Personas c/trastorno. Así, se esperaría que a mayor actividad, menos trastorno; y en este gráfico quizás pintar los puntos (y los geom_smooth¿?) según la variable categórica "Días" para que haya un color (y una regresión?) para el nivel `d1_2`, otra para el nivel `d3_4`, etc.

**Comment by saragonzalezbarcena** [comment]
El número de días a la semana que se practica actividad física es lo mismo que la frecuencia de actividad física. Sin querer nos equivocamos, y en el eje x lo que aparece es el número de personas que realiza ejercicio físico.
Por otra parte hemos intentado hacer una gráfica de regresión múltiple para cada variable categórica Días.
![image](https://user-images.githubusercontent.com/80346430/145020807-df136ece-c9af-4d00-a3c7-9fa428f9fe66.png)

**Comment by ajcanepa** [comment]
Creo que con unas superficies de ajuste y con unos niveles más fáciles de leer y entender, las conclusiones se pueden mejorar mucho. Les he agregado algo de código en el Pull Request (gh pr checkout 18)

**Comment by ajcanepa** [comment]
Si no hay más dudas de los gráficos, y ya habéis hecho el Merge del #18 , procedo a cerrar el issue.
Si tenéis más dudas lo abrimos nuevamente!

**Comment by VeraGD** [comment]
Muchas graciaas.
